### ISSUE TITLE
Experiment with multi-thread  https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9087c6b6c8895c13138c2a6d29515882

### ISSUE THREAD

**Issue by laticoda** [mkhan45/ggez-pong-tutorial#1]
Hi mkhan45, thank you for sharing your demo.
Could you please look at this:

[]([](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9087c6b6c8895c13138c2a6d29515882))

I'm trying to introduce **multi-ball with multi-threading thanks to rayon** library.

i am struggling with errors such as:
```
88 |         let _ball_iter_rayon = self.my_vec_balls.par_iter_mut().for_each(|p| p.rect.translate(p.vel));
   |                                                                              ^^^^^^ cannot borrow as mutable
```
```
error[E0499]: cannot borrow `*main_state` as mutable more than once at a time
   --> src/main.rs:200:39
    |
197 |     main_state.my_vec_balls.push(&mut main_state.ball_1);
    |                                  ---------------------- first mutable borrow occurs here
```
...
```
200 |     ggez::event::run(ctx, event_loop, main_state)
    |                                       ^^^^^^^^^^
    |                                       |
    |                                       second mutable borrow occurs here
    |                                       first borrow later used here

error: aborting due to 2 previous errors
```

**Comment by mkhan45** [comment]
Thanks for the question!

I've got a working (but not complete) version of what you want based off of your code so I'm just going to go through the diff and explain each difference:

```rust
type VecBalls = std::vec::Vec<&Ball>;
type VecBalls = std::vec::Vec<Ball>;
```
`VecBalls` should be a `Vec<Ball>` instead of a `Vec<&Ball>` because it's stored in `MainState` anyway so there's no need to complicate things with references. Since references are immutable you can't use a `Vec<&Ball>` to modify each `Ball`. You could get around this with a `Vec<&mut Ball`, but it's overcomplicated.

Since we're no longer using references, you can remove all the lifetime annotations.

```rust
let _ball_iter_rayon = self.my_vec_balls.par_iter().for_each(|p| p.as_mut().unwrap().rect.translate(p.vel));
```

`.for_each()` doesn't return anything so you shouldn't make a variable for it.
Because we're using a `Vec<Ball>` instead of a `Vec<&Ball>` or a `Vec<&mut Ball>`, this is all we need:
```rust
self.my_vec_balls.par_iter_mut().for_each(|ball| ball.rect.translate(ball.vel));
```

```rust
 main_state.my_vec_balls.push(&main_state.ball_1);
```
This doesn't work at all with a `Vec<Ball>` instead of a `Vec<&Ball>`, but realistically it doesn't get around the borrow checker either way because it would make `MainState` self referencing, so you'd have to use a `Box`. Instead, I'd just remove the `ball_1` field of `MainState` and move everything into the `my_vec_balls` field. You can easily add new balls just by pushing them

```rust
main_state.my_vec_balls.push(Ball::new());
```

___

Once all of this is done you just have to add a loop for collision and drawing. Importantly, you can't make your draw loop parallel with `rayon` because the ggez `Context` can't be sent between threads. Ask again if you have any more questions.

**Comment by laticoda** [comment]
thanks mkhan
